version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: serhioth/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/foodgram/static/
      - media_volume:/app/foodgram/media/
      - docs_volume:/app/docs/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: serhioth/foodgram_frontend:latest
    volumes:
      - frontend_build:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend_build:/usr/share/nginx/html/
      - docs_volume:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend

volumes:
  db_data:
  frontend_build:
  media_volume:
  static_volume:
  docs_volume:
