version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: serhioth/foodgram_backend:latest
    restart: always
    volumes:
      - ./static/:/app/foodgram/static/
      - ./media/:/app/foodgram/media/
      - ./docs/:/app/docs/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: serhioth/foodgram_frontend:latest
    volumes:
      - frontend_build:/usr/share/nginx/html/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend

volumes:
  nginx.conf:
  db_data:
  frontend_build:
