# Generated by Django 4.2.1 on 2023-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name', max_length=50, verbose_name='Ingredient name')),
                ('measurement_unit', models.CharField(help_text='Measurement unit', max_length=30, verbose_name='Measurement unit')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(help_text='Amount', verbose_name='Amount of ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200, verbose_name='Recipe Name')),
                ('image', models.ImageField(default=None, null=True, upload_to='recipes/images')),
                ('text', models.TextField(verbose_name='Recipe description')),
                ('cooking_time', models.PositiveIntegerField(help_text='Time of cooking', verbose_name='Time of cooking')),
                ('is_favorited', models.BooleanField(default=False)),
                ('is_in_shopping_cart', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag', max_length=30, verbose_name='Tag name')),
                ('color', models.CharField(help_text='Color', max_length=16, verbose_name='Tag color')),
                ('slug', models.SlugField(help_text='Slug', max_length=30, unique=True, verbose_name='Tag slug')),
            ],
        ),
    ]
