# Generated by Django 4.2.1 on 2023-07-31 19:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_remove_recipe_is_favorited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Amount', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество ингредиента не может быть меньше, чем 1'), django.core.validators.MaxValueValidator(limit_value=10000, message='Количество ингредиента не может быть больше, чем 10000')], verbose_name='Amount of ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Time of cooking', validators=[django.core.validators.MinValueValidator(limit_value=5, message='Время готовки не может быть меньше, чем 5'), django.core.validators.MaxValueValidator(limit_value=720, message='Время готовки не может быть больше, чем 720')], verbose_name='Time of cooking'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('author', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'color')},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Recipes tags', related_name='tagged_recipes', to='recipes.tag'),
        ),
    ]
