# Generated by Django 4.2.1 on 2023-08-08 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientamount_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name', max_length=200, verbose_name='Ingredient name'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Amount', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Amount of ingredient should not be less than 1.'), django.core.validators.MaxValueValidator(limit_value=10000, message='Amount of ingredient should not be more than 10000.')], verbose_name='Amount of ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Time of cooking', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Cooking time should not be less than 1.'), django.core.validators.MaxValueValidator(limit_value=720, message='Cooking time should not be more than 720.')], verbose_name='Time of cooking'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_recipe_name_author'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'color'), name='unique_name_color'),
        ),
    ]
