# Generated by Django 4.2.1 on 2023-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='User email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
